# Generated by Django 5.2.5 on 2025-09-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_de_entrega', models.DateField()),
                ('prioridad', models.CharField(max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
            ],
        ),
    ]
