# Generated by Django 5.2.5 on 2025-09-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='archivo',
            field=models.BooleanField(default=False),
        ),
    ]
