# Generated by Django 5.2.6 on 2025-09-28 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tareas_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='respuestas/')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='app.tareas')),
            ],
        ),
    ]
