# Generated by Django 5.2.6 on 2025-09-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='respuestas_archivos/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adicionales', to='app.respuesta')),
            ],
        ),
    ]
